# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import firstscreen

class Ui_First(object):
    def setupUi(self, First):
        First.setObjectName("First")
        First.resize(1001, 585)
        self.centralwidget = QtWidgets.QWidget(First)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1261, 761))
        self.label.setStyleSheet("background-image: url(:/newPrefix/first.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        First.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(First)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1001, 26))
        self.menubar.setObjectName("menubar")
        First.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(First)
        self.statusbar.setObjectName("statusbar")
        First.setStatusBar(self.statusbar)

        self.retranslateUi(First)
        QtCore.QMetaObject.connectSlotsByName(First)

    def retranslateUi(self, First):
        _translate = QtCore.QCoreApplication.translate
        First.setWindowTitle(_translate("First", "Tic Tac Toe - Badal"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    First = QtWidgets.QMainWindow()
    ui = Ui_First()
    ui.setupUi(First)
    First.show()
    sys.exit(app.exec_())
